.TH FFILE 1 2022-12-22 THEA Thea's\ Personal\ Manual

.SH NAME
ffile \- find a file using
.B dmenu(1)
and open it using external program.

.SH DESCRIPTION
.B ffile
opens
.B
dmenu(1)
with list of files and directories in the specified directory ($HOME by default).
The script ignores hidden files as of now. This might be subject to change.

This is alpha quality software and alpha quality manual page.

.SH EXIT STATUS
.TP
0
on success; right now no errors are reported

.SH AUTHOR
Written by Thea.

.SH COPYRIGHT
Copyright \(co Thea.
Licence GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.

.SH SEE ALSO
\fBdmenu(1)\fP, \fBopen(1)\fP
