.TH FILEBAK 1 2022-08-20 THEA Thea's\ Personal\ Manual

.SH NAME
filebak \- create a snapshot of the most recent changes to files

.SH SYNOPSIS
I have nothing to synops yet

.SH
DESCRIPTION
.\" I have no clue how the bolding below works, I saw it in some
.\" other manpage
Copy using \fBrsync\fR from predefined directories to encrypted
removable storage.

.SH EXIT STATUS
.TP
0
if everything succeeded,
.TP
1
if some operation failed.

.SH AUTHOR
Written by Thea.

.SH COPYRIGHT
Copyright \(co Thea.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.

.SH SEE ALSO
\fBrsync(1)\fP
